modLoader="javafml"
loaderVersion="[36,)"
license="LGPL"
issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="lazulib"
    version="${version}"
    displayName="${display}"
    updateJSONURL="${update_json}"
    displayURL="${page}"
    logoFile="${logo_file}"
    credits="${credits}"
    authors="${authors}"
    description='''${description}'''
[[dependencies.lazulib]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lazulib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"