modLoader="javafml"
loaderVersion="[36,)"
license="LGPL"
#issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="lazulib"
    version="${version}"
    displayName="${display}"
    #updateJSONURL="${update_json}"
    #displayURL="${page}"
    logoFile="${logo_file}"
    credits="${credits}"
    authors="${authors}"
    description='''${description}'''
[[dependencies.lazulib]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lazulib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"